# Basic
title: Vno Jekyll
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/ericQiang/ericQiang" target="_blank">Download the theme</a>
description: fork form Vno Jekyll.
creator: <a href="www.ericqiang.cn">@onevcat</a>

url: "www.ericqiang.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'www.ericqiang.cn'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
